=== angelicafreitas/DAW2020/tpc2/PR.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT pr (header, workteam, abstract, deliverables)>
<!ELEMENT header (keyname, title, subtitle?, begindate, enddate, supervisor)>

<!ELEMENT keyname (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT subtitle (#PCDATA)>
<!ELEMENT begindate (#PCDATA)>
<!ELEMENT enddate (#PCDATA)>
<!ELEMENT supervisor (#PCDATA)>
<!ATTLIST supervisor  
    url CDATA #IMPLIED>
	

<!ELEMENT workteam (worker)+>

<!ELEMENT worker (name , email, number)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ATTLIST email  
    url CDATA #IMPLIED>
<!ELEMENT number (#PCDATA)>


<!ELEMENT abstract (paragraph)+>

<!ELEMENT paragraph (#PCDATA|bold|underline|italic|link)*>
<!ELEMENT bold (#PCDATA)>
<!ELEMENT underline (#PCDATA)>
<!ELEMENT italic (#PCDATA)>
<!ELEMENT link (#PCDATA)> 
<!ATTLIST link  
    url CDATA #REQUIRED>



<!ELEMENT deliverables (link)*>

=== angelicafreitas/DAW2020/tpc2/PR.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "PR.dtd">
<pr>
    <header>
        <keyname>TPC2/DAW-2020</keyname>
        <title>DTD and XML</title>
        <begindate>October 2020</begindate>
        <enddate>October 2021</enddate>
        <supervisor url="http://www4.di.uminho.pt/~jcr/">José Carlos Ramalho</supervisor>
    </header>
    <workteam>
        <worker>
            <name>Angélica Freitas</name>
            <email>a83761@alunos.uminho.pt</email>
            <number>a83761</number>
        </worker>
    </workteam>
    <abstract>
        <paragraph><bold>DAW</bold>'s (Web Application Development) <italic>project record</italic>. 
            See original pr: <link url="http://www4.di.uminho.pt/~jcr/PROJS/micei2002/guilherme/Project%20Record.htm">original</link>
        </paragraph>
    </abstract>
    <deliverables>
        <link url="file:///home/angelica/DAW2020/tpc2/PR.dtd">DTD</link>
        <link url="file:///home/angelica/DAW2020/tpc2/PR.XML">XML</link>
    </deliverables>
</pr>

=== angelicafreitas/DAW2020/tpc3/PR.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "PR.dtd">
<pr>
    <header>
        <keyname>TPC3/DAW-2020</keyname>
        <title>DTD and XSLT</title>
        <begindate>October 2020</begindate>
        <enddate>November 2020</enddate>
        <supervisor url="http://www4.di.uminho.pt/~jcr/">José Carlos Ramalho</supervisor>
    </header>
    <workteam>
        <worker>
            <name>Angélica Freitas</name>
            <email>a83761@alunos.uminho.pt</email>
            <number>a83761</number>
        </worker>
    </workteam>
    <abstract>
        <paragraph>
            <bold>DAW</bold>'s (Web Application Development) XSLT project about archeosites. 
        </paragraph>
    </abstract>
    <deliverables>
        <link url="file:///home/angelica/DAW2020/tpc3/arq.dtd">DTD</link>
        <link url="file:///home/angelica/DAW2020/tpc3/arq.xml">XML</link>
        <link url="file:///home/angelica/DAW2020/tpc3/arq.xsl">XSLT</link>
    </deliverables>
</pr>
